import { Montserrat } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import LenisScrollProvider from "@/providers/lenis-provider";

const montserrat = Montserrat({
  style: ["normal", "italic"],
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Municipalidad de Alberti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className} antialiased text-white overflow-x-hidden bg-white`}
      >
        <LenisScrollProvider>
          <Header />
          {children}
        </LenisScrollProvider>
      </body>
    </html>
  );
}
